FROM node:14-alpine as build-step

RUN mkdir -p /app

WORKDIR /app

COPY package.json /app

RUN npm install
RUN npm install -g @angular/cli@12.1.0

# RUN ng update --next @angular/cli --force

COPY . /app

# RUN ng update --next @angular/cli --force

# RUN ng build --configuration dev

RUN ng build --configuration prod


FROM nginx

COPY --from=build-step /app/dist/cropdataMIS /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
COPY mime.types /etc/nginx/conf/mime.types

CMD ["nginx", "-g", "daemon off;"]
